### ISSUE TITLE
Updating `monarch_context`

### ISSUE THREAD

**Issue by joeflack4** [cthoyt/curies#11]
Hey @cthoyt, thanks for putting all of this together. I think for now I will pass `prefix_map` manually. I tried out the [`monarch_context`](https://raw.githubusercontent.com/prefixcommons/prefixcommons-py/master/prefixcommons/registry/monarch_context.jsonld), but as expected, some of it is out of date.

All I really checked for was to see if the `OMIMPS` (OMIM Phenotypic Series) prefix appeared, but it doesn't; I didn't really check for anything else.

I could place the onus on @matentzn to help with this at some point.

**Comment by cthoyt** [comment]
It's currently pointing to a resource in https://github.com/prefixcommons/prefixcommons-py. If you have a better URL for a more up-to-date JSON-LD context, I will happily update it

**Comment by joeflack4** [comment]
I don't, but I think Nico probably will know.

**Comment by matentzn** [comment]
@joeflack4 while we are still working out the details of the new Mondo pipelines, we do not know _exactly_ what we need yet. We will keep using this here: https://github.com/monarch-initiative/mondo-ingest/blob/4f03c3682b24a1541f9fbd9442e7dfbb27a4b43b/src/ontology/config/context.json (on your exclusion table branch)  until we have covered everything we need, and then make a concerted effort to add all missing prefixes to prefix commons or directly to bioregistry.

One particularly annoying problem we have is the fact that some of our data sources do not have official PURLs, so we need to be a bit flexible to switch out the URI expansion part whenever we change our serialisation. For example, right now we are using bioportal ICD10CM as a source in mondo, which has bioportal purls. Tomorrow we may use another source with, say, WHO uri prefixes.

**Comment by cthoyt** [comment]
Can you inform me when https://github.com/monarch-initiative/mondo-ingest/blob/4f03c3682b24a1541f9fbd9442e7dfbb27a4b43b/src/ontology/config/context.json is merged into the main branch? I'd rather link without a version so the most recent one can be retrieved

**Comment by matentzn** [comment]
Yeah we will tell you when this is stable - right now its in a state of massive flux while we are setting up the first round of our syncing pipeline!

**Comment by cthoyt** [comment]
It turns out that this context file is already available on the main branch https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/config/context.json so I pointed the PR there and will merge. It'll be up to you to get it updated nicely

**Comment by matentzn** [comment]
Wait before you use this - this file is a garbage bin for internal use at the moment. I will let you know once the correct one is there. Also, this is _not_ monarch related. This is purely about mondo!

**Comment by cthoyt** [comment]
So what was in the prefixcommons-py repository was a misnomer? Right now I think the right move is probably just close the PR and label this issue blocked upstream

**Comment by matentzn** [comment]
I will reopen this issue when the time comes - for now, its fine to close!
