### ISSUE TITLE
Public API to build a converter incrementally

### ISSUE THREAD

**Issue by kervel** [cthoyt/curies#33]
Hello,

As discussed in https://github.com/linkml/linkml-runtime/pull/244 there are usecases where it makes sense to build a converter incrementally (eg to have an API where not all prefixes are known at creation time): for instance by creating an empty converter and then adding the prefixes and schema with an  `add_prefix` function.

Thanks
Frank

**Comment by cthoyt** [comment]
Hi @kervel, this seems reasonable (though the PR you linked it very difficult to understand). I'll make a demo PR and tag you for review
