### ISSUE TITLE
curies convertor returns none instead of ignoring when it does not match anything

### ISSUE THREAD

**Issue by shawntanzk** [cthoyt/curies#63]
Hi, not sure if this is a bug of feature, but something that I thought I should write here

I am running` bioregistry_converter.pd_compress` and it shows up none when it does not match anything.
Probably not ideal (unless that is exactly what you intended) - would expect it to ignore and leave the URL if it does not match 
![image](https://github.com/cthoyt/curies/assets/76212760/da38dd2e-583b-4296-acf7-9b2a00fd2fd6)

Similar happens with ` bioregistry_converter.pd_expand` 
![image](https://github.com/cthoyt/curies/assets/76212760/29d5a08b-f782-42e7-b676-2fff71188bb4)

**Comment by cthoyt** [comment]
This is expected behavior. `curies` does not currently consider situations with ill-defined semantics, such as when you have a column that's suppose to be CURIEs but sometimes an IRI appears anyway. Two potential ways forward:

1. Make these utilties more strict and throw errors when the content of the cell isn't a valid, recognizable, parsable CURIE (within the scope of the `curies.Converter`)
2. Implement a utility that has an omni-parser that can handle situations where CURIEs or IRIs can appear in the same field

**Comment by shawntanzk** [comment]
I think an error message might be a potential fix, but I do understand that that might frustrate people (me included) - so far we have written around it (both my colleague and I in different ways) so maybe just a documentation note might suffice :) btws happy for you to close this as something you won't change, just thought I'd open this ticket as a community user :) thanks!

**Comment by hrshdhgd** [comment]
I have a similar issue. Here's my code:

```
import pyobo
from curies import get_obo_converter

obo_converter = get_obo_converter()
df = pyobo.get_sssom_df(resource, names=names)

# Remove bananas
df["object_id"] = df["object_id"].apply(lambda x: ":".join(x.split(":")[-2:]) if str(x).count(":") > 1 else x)

obo_converter.pd_standardize_curie(df, column="object_id")
print(df)
```

This gives `object_id` column to be `None`s. 

Questions:
1. I commented the code for banana removal and ran the code above. It yielded same results.
2. I know all rows in the `object_id` column are CURIEs. 
3. In a situation where not all but some elements  in the column of interest are not legitimate CURIEs , would this truncate all to `None`s?

Any suggestions would be super valuable!

**Comment by hrshdhgd** [comment]
I'd like to add: `bioregistry_converter.pd_standardize_curie(df, column="object_id")` does yield results.

**Comment by hrshdhgd** [comment]
May I suggest this code:
https://github.com/cthoyt/curies/blob/e5c56d66338dbaea3d98366dd7f3010810296c7e/src/curies/api.py#L990-L1010

to be updated as 

```
def standardize_prefix(self, prefix: str) -> Optional[str]:
        """Standardize a prefix.

        :param prefix:
            The prefix of the CURIE
        :returns:
            The standardized version of this prefix wrt this converter.
            If the prefix is not registered in this converter, returns none.

        >>> from curies import Converter, Record
        >>> converter = Converter.from_extended_prefix_map([
        ...     Record(prefix="CHEBI", prefix_synonyms=["chebi"], uri_prefix="..."),
        ... ])
        >>> converter.standardize_prefix("chebi")
        'CHEBI'
        >>> converter.standardize_prefix("CHEBI")
        'CHEBI'
        >>> converter.standardize_prefix("NOPE") is None
        True
        """
        if prefix.lower() in [k.lower() for k in self.synonym_to_prefix.keys()]:
            standardized_prefix = [v for k, v in self.synonym_to_prefix.items() if k.lower() == prefix.lower()][0]
        else:
            standardized_prefix = prefix # default was None
        return standardized_prefix
```

This way:
- Even if there is no standardized version for a `prefix` It returns the same as before instead of `None`
- Makes the `prefix` case-insensitive and makes sure `.upper()` / `.lower()` / mixed case `prefix`es are still caught and standardized.

Thoughts?

**Comment by cthoyt** [comment]
> I have a similar issue. Here's my code:
> 
> ```
> import pyobo
> from curies import get_obo_converter
> 
> obo_converter = get_obo_converter()
> df = pyobo.get_sssom_df("umls", names=False)
> 
> # Remove bananas
> df["object_id"] = df["object_id"].apply(lambda x: ":".join(x.split(":")[-2:]) if str(x).count(":") > 1 else x)
> 
> obo_converter.pd_standardize_curie(df, column="object_id")
> print(df)
> ```
> 
> This gives `object_id` column to be `None`s.
> 
> Questions:
> 
>     1. I commented the code for banana removal and ran the code above. It yielded same results. (I understand the banana removal process may not be accurate but trying to get this working for now).
> 
>     2. I know all rows in the `object_id` column are CURIEs.
> 
>     3. In a situation where not all but some elements  in the column of interest are not legitimate CURIEs , would this truncate all to `None`s?
> 
> 
> Any suggestions would be super valuable!
> 
> UPDATE:
> 
>     * I'd like to add: `bioregistry_converter.pd_standardize_curie(df, column="object_id")` does yield results but I specifically need OBO format for prefixes.
> 
>     * `get_monarch_converter()` returns `None`s as well

This is a different issue, @hrshdhgd can you please open a new thread and move the last two comments?

**Comment by hrshdhgd** [comment]
https://github.com/cthoyt/curies/issues/72
