### ISSUE TITLE
How does `curies` handle uri prefix ordings?

### ISSUE THREAD

**Issue by matentzn** [cthoyt/curies#8]
I tried to understand it from the code but I was not sure. 

```
'GO': 'http://purl.obolibrary.org/obo/GO_`
'obo': 'http://purl.obolibrary.org/obo/`
```

How can I parse `http://purl.obolibrary.org/obo/GO_` to:

`GO:123`

vs 

`obo:GO_123`?

I am not saying I want to I just need to know how this is handled. Thanks :)

(my preference would be sorting the prefixmap so the longest match always gets precedence, i.e. `obo:GO_123` _never_ happens.).

**Comment by cthoyt** [comment]
This repository uses a prefix trie (i.e., trie), which is specifically built to match the longest of several potentially overlapping URIs. In fact, there is actually no possible way to get `obo:GO_123`, even if desired, using this implementation.

**Comment by matentzn** [comment]
So what happens if I 

1. try to curify `http://purl.obolibrary.org/obo/GO_` and I pass in a custom prefix map (with only the `obo` prefix):

```
'obo': 'http://purl.obolibrary.org/obo/`
```

or 

2. try to curify `http://purl.obolibrary.org/obo/uberon`?:

```
'GO': 'http://purl.obolibrary.org/obo/GO_`
'obo': 'http://purl.obolibrary.org/obo/`
```

**Comment by cthoyt** [comment]
This repository has no notion of a "custom prefix map". Take whatever prefix map you want (customized to your liking), instantiate the `Converter` class with it, then you can run the `compress` function on `http://purl.obolibrary.org/obo/uberon`. 

```python
from curies import Coverter
converter = Converter.from_prefix_map({
  'GO': 'http://purl.obolibrary.org/obo/GO_`
  'obo': 'http://purl.obolibrary.org/obo/`
})
>>> converter.compress('http://purl.obolibrary.org/obo/uberon')
'OBO:uberon'
```

**Comment by matentzn** [comment]
`Take whatever prefix map you want` -> Thats what I meant but custom. I just stumbled across:

> In fact, there is actually no possible way to get obo:GO_123, even if desired, using this implementation.

As an aside, hwo did the `OBO` end up upper case in your example :P?

**Comment by cthoyt** [comment]
i thought you liked uppercase :p

should I lowercase it?

**Comment by matentzn** [comment]
Excellent @cthoyt thank you!
