### ISSUE TITLE
Add is_curie() and is_uri() methods as helper functions

### ISSUE THREAD

**Issue by matentzn** [cthoyt/curies#89]
Compression and expansion are not the only use cases for curies, we sometimes just want to know if a string is a curie or not. I keep writing wrappers with curies.parse... methods and it would be nice if this was somehow natively supported.

**Comment by cthoyt** [comment]
Related https://github.com/cthoyt/curies/issues/77

**Comment by cthoyt** [comment]
@matentzn can you add some details on places where you would like to use this functionality?

**Comment by matentzn** [comment]
In OAK, the relationships are randomly curies when the URI prefix is known (is in the map) and URIs otherwise. For certain applications, I just want to skip all cases where the relationships don't have a valid entry in the prefix map.

But there are a lot of applications for example in data validation, where I want to spit a warning when something is a URI but should be a curie.
